# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc_server/ia_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/grpc_server/ia_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n app/grpc_server/ia_service.proto\x12\nia_service\"\x1c\n\tCVRequest\x12\x0f\n\x07\x63v_text\x18\x01 \x01(\t\"\x1f\n\nCVResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t\"8\n\x0cMatchRequest\x12\x0f\n\x07\x63v_json\x18\x01 \x01(\t\x12\x17\n\x0fjob_description\x18\x02 \x01(\t\"1\n\rMatchResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x12\x11\n\treasoning\x18\x02 \x01(\t2\x8d\x01\n\tAIService\x12\x38\n\x07ParseCV\x12\x15.ia_service.CVRequest\x1a\x16.ia_service.CVResponse\x12\x46\n\x0fGetInstantMatch\x12\x18.ia_service.MatchRequest\x1a\x19.ia_service.MatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc_server.ia_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CVREQUEST']._serialized_start=48
  _globals['_CVREQUEST']._serialized_end=76
  _globals['_CVRESPONSE']._serialized_start=78
  _globals['_CVRESPONSE']._serialized_end=109
  _globals['_MATCHREQUEST']._serialized_start=111
  _globals['_MATCHREQUEST']._serialized_end=167
  _globals['_MATCHRESPONSE']._serialized_start=169
  _globals['_MATCHRESPONSE']._serialized_end=218
  _globals['_AISERVICE']._serialized_start=221
  _globals['_AISERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
