# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_server import ia_service_pb2 as app_dot_grpc__server_dot_ia__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/grpc_server/ia_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseCV = channel.unary_unary(
                '/ia_service.AIService/ParseCV',
                request_serializer=app_dot_grpc__server_dot_ia__service__pb2.CVRequest.SerializeToString,
                response_deserializer=app_dot_grpc__server_dot_ia__service__pb2.CVResponse.FromString,
                _registered_method=True)
        self.GetInstantMatch = channel.unary_unary(
                '/ia_service.AIService/GetInstantMatch',
                request_serializer=app_dot_grpc__server_dot_ia__service__pb2.MatchRequest.SerializeToString,
                response_deserializer=app_dot_grpc__server_dot_ia__service__pb2.MatchResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseCV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstantMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseCV': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseCV,
                    request_deserializer=app_dot_grpc__server_dot_ia__service__pb2.CVRequest.FromString,
                    response_serializer=app_dot_grpc__server_dot_ia__service__pb2.CVResponse.SerializeToString,
            ),
            'GetInstantMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstantMatch,
                    request_deserializer=app_dot_grpc__server_dot_ia__service__pb2.MatchRequest.FromString,
                    response_serializer=app_dot_grpc__server_dot_ia__service__pb2.MatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ia_service.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ia_service.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseCV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ia_service.AIService/ParseCV',
            app_dot_grpc__server_dot_ia__service__pb2.CVRequest.SerializeToString,
            app_dot_grpc__server_dot_ia__service__pb2.CVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstantMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ia_service.AIService/GetInstantMatch',
            app_dot_grpc__server_dot_ia__service__pb2.MatchRequest.SerializeToString,
            app_dot_grpc__server_dot_ia__service__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
