version: '3.9'

services:
  ia-service:
    build: .
    container_name: ia-service
    ports:
      - "8000:8000"
      - "50051:50051" # gRPC
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - infra

networks:
  infra:
    external: true
